spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/oauth
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update    # 개발용 only
    show-sql: true

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG